workflows:
  ios-workflow:
    name: iOS Build OBPC
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/ios @capacitor/core @capacitor/cli
      - name: Capacitor Sync
        script: |
          # Isso vai aplicar o novo ID br.com.obpcschool no projeto nativo
          npx cap sync ios
      - name: Build iOS (.ipa)
        script: |
          cd ios/App
          agvtool new-version -all $(date +%Y%m%d%H%M)
          
          # Tenta usar os perfis (Garanta que o perfil no site é br.com.obpcschool)
          xcode-project use-profiles --warn-only
          
          xcode-project build-ipa \
            --project "App.xcodeproj" \
            --scheme "App" \
            --clean
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - ferna@example.com
