workflows:
  ios-workflow:
    name: iOS Build OBPC
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/ios @capacitor/core @capacitor/cli
      - name: Capacitor Sync
        script: |
          # Sincroniza a pasta /www que já existe no seu projeto
          npx cap sync ios
      - name: Build iOS (.ipa)
        script: |
          # Compila o projeto nativo usando os certificados que você subiu no painel
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - ferna@example.com
