workflows:
  ios-workflow:
    name: iOS Build OBPC
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/ios @capacitor/core @capacitor/cli
      - name: Capacitor Sync
        script: |
          npx cap sync ios
      - name: Build iOS (.ipa)
        script: |
          cd ios/App
          # Atualiza a versão para evitar conflito na Apple
          agvtool new-version -all $(date +%Y%m%d%H%M)
          
          # Instala os certificados do painel do Codemagic
          xcode-project use-profiles
          
          # Executa o build
          xcode-project build-ipa \
            --project "App.xcodeproj" \
            --scheme "App" \
            --clean
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - ferna@example.com
